---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-agents
---
apiVersion: v1
kind: Secret
metadata:
  name: kanikoazdosecret
  namespace: docker-agents
data:
  AZP_TOKEN: "__azdo-pat-enc__"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-agents
  namespace: docker-agents
  labels:
    name: docker-agents
spec:
  replicas: 6
  selector:
    matchLabels:
      app: docker-agents
  template:
    metadata:
      labels:
        app: docker-agents

    spec:
      imagePullSecrets:
      - name: docker-registry-credentials
      containers:
      - name: docker-agents
        image: dockeragent.azurecr.io/docker-agents:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
          limits:
            memory: 8Gi
            cpu: 2000m
        env:
        - name: AZP_URL
          value: "https://dev.azure.com/harshitbisht"
        - name: AZP_POOL
          value: "docker-agent"
        - name: AZP_TOKEN
          valueFrom:
             secretKeyRef:
               name: kanikoazdosecret
               key: AZP_TOKEN